name: documentation

on:
  push:
    branches:
      - dev

jobs:
  docs:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get git tags
        run: git fetch --tags origin/dev

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -mpip install .
          python -mpip install ".[docs]"

      - name: Sphinx build
        run: |
          sphinx-build docs/_source docs/_build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true