name: documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: '0'

      - name: Get git tags
        run: git fetch --tags origin

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -mpip install .
          python -mpip install ".[docs]"

      - name: Sphinx build
        run: |
          sphinx-build docs/_source docs/_build
          touch docs/_build/.nojekyll
          ls -la docs/_build/

#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v4
#        with:
#          publish_branch: gh-pages
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: docs/_build/
#          force_orphan: true

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: docs/_build/


  # Deployment job
  deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
